### ISSUE TITLE
Utilizar o ElasticSearch como mecanismo padrão de busca

### ISSUE THREAD

**Issue by brenowschneider** [prodest/processo-eletronico-web-api#10]
1. Identificação e definição de um servidor para o ElasticSearch #23
2. Indexar documentos no servidor do Elastic Search #17 
3. O ElasticSearch deve ser o mecanismo de busca padrão

**Comment by viniciusgazzoli** [comment]
1. Indexar documentos no servidor do Elastic Search
2. Implementar a consulta por número de processos no Elastic Search
3. Ao inserir um registro no banco de dados, atualizar o indice no Elastic Search

**Comment by brenowschneider** [comment]
Biblioteca do elastic search foi adicionada no projeto (em Infraestrutura)
