### ISSUE TITLE
Implementar métodos de edição para os recursos auxiliares

### ISSUE THREAD

**Issue by viniciusgazzoli** [prodest/processo-eletronico-web-api#114]

**Comment by viniciusgazzoli** [comment]
Avaliar quais entidades poderão ser editadas conforme regra de negócio

**Comment by brenowschneider** [comment]
Essa issue não é mais válida, uma vez que plano de classificação, função, atividade e tipo documental são entidades que serão controladas no sistema de classificação documental.
