### ISSUE TITLE
Indexar uma amostra com 1000 documentos no servidor do Elastic Search

### ISSUE THREAD

**Issue by viniciusgazzoli** [prodest/processo-eletronico-web-api#17]

**Comment by brenowschneider** [comment]
1000 documentos foram indexados no índice "processoeletronico" no tipo "processo".
O endereço do tipo é <servidor elasticsearch>/processoeletronico/processo.

Como exemplo de documento:

{
"numero":56876938,
"digito":4,
"resumo":"Aliquip irure officia pariatur occaecat excepteur et est. Consequat laborum nisi aliqua enim enim labore dolor aliquip excepteur ut laborum sint Lorem. Ut reprehenderit laborum do cupidatat ad incididunt exercitation elit dolore sint voluptate excepteur incididunt consequat. Adipisicing culpa Lorem minim amet ut est laboris quis ullamco. Exercitation et ad sunt sint exercitation sunt occaecat officia aliquip qui elit laboris aliqua. Velit irure sunt laboris aliqua est cillum reprehenderit aute quis amet ex.\r\n",
"orgao_autuacao": {"id":3,"sigla":"TJ-ES"},
"data_autuacao":"29/05/2016",
"assunto":{"id":1,"descricao":"Apólice"}}

**Comment by brenowschneider** [comment]
1000 documentos foram indexados no índice "processoeletronico" no tipo "processo".
O endereço do tipo é /processoeletronico/processo.

Como exemplo de documento:

{
"numero":56876938,
"digito":4,
"resumo":"Aliquip irure officia pariatur occaecat excepteur et est. Consequat laborum nisi aliqua enim enim labore dolor aliquip excepteur ut laborum sint Lorem. Ut reprehenderit laborum do cupidatat ad incididunt exercitation elit dolore sint voluptate excepteur incididunt consequat. Adipisicing culpa Lorem minim amet ut est laboris quis ullamco. Exercitation et ad sunt sint exercitation sunt occaecat officia aliquip qui elit laboris aliqua. Velit irure sunt laboris aliqua est cillum reprehenderit aute quis amet ex.\r\n",
"orgao_autuacao": {"id":3,"sigla":"TJ-ES"},
"data_autuacao":"29/05/2016",
"assunto":{"id":1,"descricao":"Apólice"}}

**Comment by brenowschneider** [comment]
1000 documentos foram indexados no índice "processoeletronico" no tipo "processo".
O endereço do tipo é /processoeletronico/processo.

Como exemplo de documento:

<
{
"numero":56876938,
"digito":4,
"resumo":"Aliquip irure officia pariatur occaecat excepteur et est. Consequat laborum nisi aliqua enim enim labore dolor aliquip excepteur ut laborum sint Lorem. Ut reprehenderit laborum do cupidatat ad incididunt exercitation elit dolore sint voluptate excepteur incididunt consequat. Adipisicing culpa Lorem minim amet ut est laboris quis ullamco. Exercitation et ad sunt sint exercitation sunt occaecat officia aliquip qui elit laboris aliqua. Velit irure sunt laboris aliqua est cillum reprehenderit aute quis amet ex.\r\n",
"orgao_autuacao": {"id":3,"sigla":"TJ-ES"},
"data_autuacao":"29/05/2016",
"assunto":{"id":1,"descricao":"Apólice"}}
>
