### ISSUE TITLE
Manter Pendência

### ISSUE THREAD

**Issue by viniciusgazzoli** [prodest/processo-eletronico-web-api#37]
7.7.1.  Narrativa
Como um usuário do sistema devo manter pendência para ser utilizada no andamento do processo para que se possa acompanhar os motivos que impedem a sua tramitação. 

7.7.2.  Premissas
Serão utilizadas pendências mantidas pelo sistema.
A lista de pendência apresentada deverá ser filtrada, para exibir de acordo com o órgão do usuário que estiver utilizando.
Todo registro de informação de pendência processual será auditado.
Toda mudança deverá ser registrada em auditoria.
Esta estória de usuário é de acesso restrito e necessita de autenticação.

**Comment by brenowschneider** [comment]
As pendências de um processo são determinada pela sua atuação e seus despachos. Dessa forma, essa funcionalidade não é necessária.
