### ISSUE TITLE
EU015 – Consultar Processo

### ISSUE THREAD

**Issue by viniciusgazzoli** [prodest/processo-eletronico-web-api#45]
7.15.1. Narrativa
Como um usuário do sistema devo consultar um processo considerando filtragens, indexadores e recursos de taxonomia para que haja celeridade na recuperação de informações processuais.

7.15.2. Premissas
Toda consulta e navegação do sistema será auditada.
Esse serviço deverá ter documentação conforme referências: Documentação wiki do código: https://github.com/paypal/PayPal-NET-SDK/wiki. Documentação API: https://developer.paypal.com/docs/api/.
Esta estória de usuário é de acesso público, mas também tem informações de acesso restrito.

**Comment by brenowschneider** [comment]
Consulta de processos concluída.
