### ISSUE TITLE
EU016 – Despachar Processo

### ISSUE THREAD

**Issue by viniciusgazzoli** [prodest/processo-eletronico-web-api#46]
7.16.1. Narrativa
Como um usuário do sistema devo analisar um documento recebido e registrar a análise efetuada para que sua decisão ou recomendação seja conhecida e formalizada.

7.16.2. Premissas
Será possível anexar documento (s) a cada despacho.
Cada despacho será assinado digitalmente.
A assinatura através de utilização de certificado digital deverá possuir raiz IPC-Brasil ou que for definido pela entidade competente.
Não poderão ser usados certificados fora da validade e revogados.
O usuário que efetuar o despacho classificará o documento conforme a LAI e de acordo com sua competência.
O usuário que efetuar o despacho poderá sinalizar o processo se necessário. 
O usuário que efetuar o despacho poderá informar a pendência processual se necessário.
Todo despacho será auditado.
Esse serviço deverá ter documentação conforme referências: Documentação wiki do código: https://github.com/paypal/PayPal-NET-SDK/wiki. Documentação API: https://developer.paypal.com/docs/api/.
Esta estória de usuário é de acesso restrito e necessita de autenticação.

**Comment by brenowschneider** [comment]
Despacho de processos concluído.
