### ISSUE TITLE
EU017 – Tramitar Processo

### ISSUE THREAD

**Issue by viniciusgazzoli** [prodest/processo-eletronico-web-api#47]
7.17.1. Narrativa
Como um usuário do sistema devo registrar o deslocamento do processo de um setor para o outro para que haja rastreabilidade e localização atual do processo.
7.17.2. Premissas
Os andamentos serão identificados de forma única.
Todo andamento será auditado.
Esse serviço deverá ter documentação conforme referências: Documentação wiki do código: https://github.com/paypal/PayPal-NET-SDK/wiki. Documentação API: https://developer.paypal.com/docs/api/.
Esta estória de usuário é de acesso restrito e necessita de autenticação.
7.17.3. Fora do Escopo
A tramitação do processo não se dará fora do Poder Executivo de Esfera Estadual.

**Comment by brenowschneider** [comment]
Tramitação é determinada pela autução e pelos despachos do processos. Essas funcionalidades já estão implementadas.

**Comment by brenowschneider** [comment]
Tramitação é determinada pela autução e pelos despachos do processos. Essas funcionalidades já estão implementadas.
