### ISSUE TITLE
EU030 – Autuação de Processo

### ISSUE THREAD

**Issue by viniciusgazzoli** [prodest/processo-eletronico-web-api#60]
7.30.1. Narrativa
Como um usuário eu quero atualizar as informações de interessados de modo que eu não necessite informar o número do telefone fixo.

7.30.2. Premissas
Esta estória de usuário é de acesso restrito e necessita de autenticação.
As ações sofridas por um processo deverão ser auditadas.

**Comment by brenowschneider** [comment]
Autução de processos concluída.
