### ISSUE TITLE
EU035 – Consulta pública de processo

### ISSUE THREAD

**Issue by viniciusgazzoli** [prodest/processo-eletronico-web-api#65]
7.35.1. Narrativa
Como um cidadão eu quero consultar processos na internet de modo que possa ver as informações públicas inseridas na autuação do processo e também o seu andamento.

7.35.2. Premissas
Esta estória de usuário é de acesso público e não necessita de autenticação.

**Comment by brenowschneider** [comment]
Consulta de processos implementada. Lembrando que apesar da consulta ser pública, o usuário deve estar logado no acesso cidadão.
