### ISSUE TITLE
Documentar principais características do PEN

### ISSUE THREAD

**Issue by viniciusgazzoli** [prodest/processo-eletronico-web-api#67]
Produzir um documento a ser publicado no repositório processo-eletrônico. Buscar identificar características que venham compor o sistema de Processo Eletrônico.

**Comment by brenowschneider** [comment]
Algumas informações a respeito do Sistema Eletrônico de Informações (SEI):
É um sistema desenvolvimento pelo TRF 4ª região (RS). O código dele é **aberto** e versionado no Git.
Segue links úteis:

**Repositórios**:
https://softwarepublico.gov.br/gitlab/sei/sei-vagrant
https://softwarepublico.gov.br/gitlab/sei/sei-db-ref-executivo (Banco de Dados)

**Guia para configuração de ambiente de desenvolvimento**:
https://softwarepublico.gov.br/gitlab/sei/sei-vagrant/blob/master/README.md

**Documentação de Apoio**:
https://softwarepublico.gov.br/social/sei/manuais/documentacao-de-apoio
